### ISSUE TITLE
Make poll_until_finished less chatty and less frequent

### ISSUE THREAD

**Issue by ninsbl** [actinia-org/actinia-python-client#11]
Currently the `poll_until_finished()` method is polling quite frequent and a bit chatty.

It would be good to add an option to

1. print only at status change and to 
2. sleep until next poll

**Comment by anikaweinmann** [comment]
This will be added in https://github.com/actinia-org/actinia-python-client/pull/15

**Comment by ninsbl** [comment]
Fixed with #15
