### ISSUE TITLE
Visualize output

### ISSUE THREAD

**Issue by mmacata** [actinia-org/actinia-python-client#18]
Currently for ephemeral processing, it would be nice to have an example how the result can be retrieved from actinia and then rendered within the jupyter notebook.

**Comment by neteler** [comment]
This could be done with [leafmap](https://leafmap.org).

See here for a related jupyter notebook:
https://leafmap.org/notebooks/42_create_cog/

**Comment by neteler** [comment]
Done in #20:

https://github.com/actinia-org/actinia-python-client/blob/main/notebooks/actinia_leafmap.ipynb
